#!/bin/sh

# Copyright © 2016-2020 Jakub Wilk <jwilk@jwilk.net>
# Copyright © 2024 Christopher Bock <christopher@bocki.com>
# SPDX-License-Identifier: MIT

set -e -u

orig_ssh_add=$(command -v -p ssh-add) || {
    printf 'ssh-add: command not found\n' >&2
    exit 127
}

if [ $# -eq 1 ]; then
    if [ -z "${1%%*.gpg}" ]; then
        [ -e "$1" ] || return
        gpg -q -d < "$1" | "$orig_ssh_add" -
    exit 0
    fi
fi

if [ $# != 0 ]
then
    exec "$orig_ssh_add" "$@"
fi

for pubkey in ~/.ssh/gpg.d/*.pub
do
    seckey="${pubkey%.pub}.gpg"
    [ -e "$seckey" ] || continue
    gpg -q -d < "$seckey" | "$orig_ssh_add" -
done

# vim:ts=4 sts=4 sw=4 et
